export default {
  LOAD_FLATS: 'LOAD_FLATS',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  ADD_FAVORITE: 'ADD_FAVORITE',
  FILTER_FLATS: 'FILTER_FLATS',
  FILTER_FLATS_FACE: 'FILTER_FLATS_FACE',
  REVIEW_FLAT: 'REVIEW_FLAT',
};
